name: devpace
description: devpace test app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: 3.10.4

dependencies:
  flutter:
    sdk: flutter

  bloc: 8.1.2
  flutter_bloc: 8.1.3
  logger: 1.4.0
  cupertino_icons: 1.0.5
  shared_preferences: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

